create table horses (
	id BIGSERIAL PRIMARY KEY NOT NULL,
	first_name VARCHAR(50) NOT NULL,
	last_name VARCHAR(50) NOT NULL,
	email VARCHAR(50) NOT NULL,
	gender VARCHAR(50) NOT NULL,
	picture VARCHAR(50),
	biography TEXT,
    body_height INT NOT NULL DEFAULT 0,
	body_length INT NOT NULL DEFAULT 0,
	city VARCHAR(50),
	country VARCHAR(50),
	is_active BOOLEAN DEFAULT false,
	last_active_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);